name: Update Recent Activity

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitHub Recent Activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Ensure this secret exists and is valid
        with:
          USERNAME: shahxhussain  # Make sure the action expects this input
          MAX_LINES: 10

      - name: Debug Output
        run: echo "Workflow completed. Check the logs for details."
